---
hosts: 172.31.31.128
become: yes
vars:
    var1: git
    var2: tree
    var3: wget
tasks:
-  name: display my var1
   debug:
     msg:"{{var1}}"
-  name: execute hostname linux command
   command: hostname -f
   register: myresult

-  name: display myresult
   debug:
      msg: "{{myresult}}"
- name: install git
  apt:
    name: git
    state: present
  when: myresult.stderr ==""

- name: install tree
  apt:
    name: tree
    state: present
  when: myresult.stderr !=""