---
- hosts: webservers
  become: yes
  tasks:
  - name: Install webserver on ubuntu
    apt:
      name: "{{mywebserveronUbuntu}}"
      state: present
    when: ansible_os_family =="Debian"

  - name: start webserver on ubuntu
    service:
      name: "{{mywebserveronUbuntu}}"
      state: started
    when: ansible_os_family =="Debian"


  - name: Insatall webserver on RedHat
    yum:
      name: "{{mywebserveronRedhat}}"
      state: present
    when: ansible_os_family =="RedHat"

  - name: start webserver on RedHat
    service:
      name: "{{mywebserveronRedhat}}"
      state: started
    when: ansible_os_family =="RedHat"